name: Check Dependencies Changes

# Install => Diff (env.PACKAGE_FILE) => Pick slack with output
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check-packages:
    name: Check packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Get Diff
        uses: tj-actions/changed-files@v45
        id: get-diff
        with:
          files: |
            package.json
            yarn.lock
            package-lock.json
        #   files: |
            # ${{ vars.PACKAGE_MANAGER_FILES }}




      - name: Output
        if: steps.get-diff.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.get-diff.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
            echo "Diff is:"
            git diff --ignore-space-at-eol --text $file
            echo "Diff 2 is:"
            git diff --ignore-space-at-eol --text HEAD~1 $file
          done
