name: Check Dependencies Changes

# Install => Diff (env.PACKAGE_FILE) => Pick slack with output
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check-packages:
    name: Check packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Get Diff
        uses: tj-actions/changed-files@v45
        id: get-diff
        with:
          files: |
            package.json
            yarn.lock
            package-lock.json
        #   files: |
            # ${{ vars.PACKAGE_MANAGER_FILES }}




      - name: Output
        if: steps.get-diff.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.get-diff.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
            echo "Diff is:"
            git diff --ignore-space-at-eol --text $file
            echo "Diff 2 is:"
            git diff --ignore-space-at-eol --text HEAD~1 $file
          done


      - name: Send Slack Notification
        if: steps.get-diff.outputs.any_changed == 'true'
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          slack-message: >
            🚨 Dependency changes detected in the repository!
            Files changed:
            ${{ steps.get-diff.outputs.all_changed_files }}
            Please review the changes: ${{ github.event.pull_request.html_url || github.server_url }}/commit/${{ github.sha }}
          # channel-id: YOUR_CHANNEL_ID
          # slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
