name: Check Dependencies Changes

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check-packages:
    name: Check packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Current path
        run: pwd
      - name: List files
        run: ls -la

      - name: Get Diff

        uses: tj-actions/changed-files@v45

        id: get-diff
        with:
          files: |
            ./infra/package.json
            ./backend/requirements.txt
            ./backend/requiremenets-dev.txt

      - name: Send Slack Notification
        if: steps.get-diff.outputs.any_changed == 'true'
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload-file-path: ./.github/templates/slack-payload.json
          payload-templated: true
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          FILES_CHANGED: ${{ steps.get-diff.outputs.all_changed_files }}
          DOCUMENTS_URL: ${{ secrets.DOCUMENTS_URL }}
          COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
