name: Check Dependencies Changes

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check-packages:
    name: Check packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Get Diff
        uses: tj-actions/changed-files@v45
        id: get-diff
        with:
          files: |
            package.json
            package-lock.json

      - name: Send Slack Notification
        if: steps.get-diff.outputs.any_changed == 'true'
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: >
            {
            "blocks": [
              {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "${{ github.repository }}"
                  }
              },
              {
                "type": "section",
                "text": {
                  "text": "🚨 Dependency changes detected.\n
                  Please review the changes and update Software Bill Of Materials if necessary.",
                  "type": "mrkdwn"
                }
              },
              		{
                "type": "divider"
              },
              {
                "type": "section",
                "text": {
                  "text": "*Files changed:* ${{ steps.get-diff.outputs.all_changed_files }}",
                  "type": "mrkdwn"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "actions",
                "block_id": "actionblock789",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Update Documents"
                    },
                    "style": "primary",
                    "url": "${{ secrets.DOCUMENTS_URL }}"
                  },
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Changes"
                    },
                    "url": "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
                  }
                ]
              }
            ]
            }
