name: Simple Git Diff

on:
  push:
    branches:
      - main
      - staging
      - dev
      - buffer

jobs:
  diff:
    name: Simple Git Diff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Changelog from S3
        uses: ./.github/actions/git-diff-s3
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          aws-bucket-name: everbeat-github

      - name: Show external changelog
        run: |
          echo -e "\n🚀 CHANGELOG:\n$CHANGELOG"
        env:
          CHANGELOG: ${{ env.CHANGELOG }}
