name: Git Diff

on:
  push:
    branches:
      - main
      - staging
      - dev
      - buffer

jobs:
  get-diff:
    name: Get Git Diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Latest Changes
        env:
          BEFORE_REF: ${{ github.event.before }}
          AFTER_REF: ${{ github.event.after }}
        run: |
          LOG=$(git log --pretty=format:"%s" "$BEFORE_REF..$AFTER_REF" | sed ':a;N;$!ba;s/\n/\\n/g')
          echo "COMMITS=$LOG" >> $GITHUB_ENV
      - name: Print Commits
        run: |
          echo "Commits: ${{ env.COMMITS }}"
