name: "Pull request labeler"

on:
  workflow_dispatch:
    # pull_request:
    # push:
    #   branches:
    #     - never

jobs:
  scan-pull-request-status:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: "merge conflicts"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_RETRIES: 5
          WAIT_MS: 5000
