name: "Pull request labeler"

on:
    pull_request:
    push:
      branches:
        - main

jobs:
  scan-pull-request-status:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Cache build files
        uses: actions/cache@v2
        with:
          path: ${{ PATH_TO_CACHE }}
          key: ${{ runner.os }}-${{ github.sha }}
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: "merge conflicts"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_RETRIES: 5
          WAIT_MS: 5000
