name: Git Diff

on:
  push:
    branches:
      - main
      - staging
      - dev
      - buffer

jobs:
  get-diff:
    name: Get Git Diff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download last successful SHA from S3
        run: |
          aws s3 cp s3://everbeat-github/changelog/last_successful_sha.txt last_successful_sha.txt || true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: your-region

      - name: Calculate Changelog
        run: |
          LAST_SHA=$(cat last_successful_sha.txt 2>/dev/null || git rev-list --max-parents=0 HEAD)
          echo "LAST SUCCESSFUL SHA: $LAST_SHA"
          echo "CURRENT COMMIT: ${{ github.sha }}"

          LOG=$(git log --pretty=format:"%s" $LAST_SHA..${{ github.sha }})
          echo -e "\n📝 CHANGELOG:\n$LOG"

          echo 'CHANGELOG<<EOF' >> $GITHUB_ENV
          echo "$LOG" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Show Changelog
        run: |
          echo -e "\n🚀 CHANGELOG:\n$CHANGELOG"
        env:
          CHANGELOG: ${{ env.CHANGELOG }}

      - name: Save new SHA to S3
        if: success()
        run: |
          echo "${{ github.sha }}" > last_successful_sha.txt
          aws s3 cp last_successful_sha.txt s3://everbeat-github/changelog/last_successful_sha.txt
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
