name: Git Diff

on:
  push:
    branches:
      - main
      - staging
      - dev
      - buffer

jobs:
  get-diff:
    name: Get Git Diff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download previous BEFORE_REF from S3 (if any)
        run: |
          aws s3 cp s3://everbeat-github/changelog/${{ github.repository }}/${{ github.ref_name }}/last_failed_before_ref.txt last_failed_before_ref.txt || true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
      - name: Get Commit Messages
        env:
          BEFORE_REF: ${{ github.event.before }}
          AFTER_REF: ${{ github.event.after }}
        run: |
          REAL_BEFORE=$(cat last_failed_before_ref.txt 2>/dev/null || echo "$BEFORE_REF")

          echo "BEFORE: $REAL_BEFORE"
          echo "AFTER: $AFTER_REF"

          LOG=$(git log --pretty=format:"%s" "$REAL_BEFORE..$AFTER_REF")

          echo 'CHANGELOG<<EOF' >> $GITHUB_ENV
          echo "$LOG" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Show Changelog
        run: |
          echo -e "\n🚀 CHANGELOG:\n$CHANGELOG"
        env:
          CHANGELOG: ${{ env.CHANGELOG }}

      - name: Simulate failure on dev only
        if: github.ref_name == 'dev'
        run: |
          echo "💥 Simulating failure on dev branch"
          exit 1


      - name: Save BEFORE_REF to S3 on failure
        if: failure()
        run: |
          echo "${{ github.event.before }}" > last_failed_before_ref.txt
          aws s3 cp last_failed_before_ref.txt s3://everbeat-github/changelog/${{ github.repository }}/${{ github.ref_name }}/last_failed_before_ref.txt
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
      - name: Delete failed BEFORE_REF from S3 on success
        if: success()
        run: |
          aws s3 rm s3://everbeat-github/changelog/${{ github.repository }}/${{ github.ref_name }}/last_failed_before_ref.txt || true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
